name: feature_settings
description: A new Flutter plugin project.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  core_common:
    path: ../../core/common
  core_model:
    path: ../../core/model
  core_data:
    path: ../../core/data
  core_domain:
    path: ../../core/domain
  core_styleguide:
    path: ../../core/styleguide
  core_ui:
    path: ../../core/ui

  plugin_platform_interface: ^2.0.2
  hooks_riverpod: ^2.0.2
  go_router: ^8.0.0
  flutter_line_sdk: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  core_testing:
    path: ../../core/testing

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
