name: feature_settings_example
description: Demonstrates how to use the feature_settings plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  feature_settings:
    path: ../

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
