name: NITO
repository: https://github.com/2rabs/nito

sdkPath: .fvm/flutter_sdk

packages:
  - apps/**
  - packages/**

ide:
  intellij:
    enabled: true

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  format:
    run: |
      melos exec -- \
        flutter format --dry-run --set-exit-if-changed lib/
    description: Format in all packages
    packageFilters:
      flutter: true
      dirExists: lib

  test:
    run: |
      melos exec --fail-fast -- \
        flutter test --coverage
    description: flutter test in all packages
    packageFilters:
      flutter: true
      dirExists: test

  gen:
    run: |
      melos exec -- \
        flutter pub run build_runner build --delete-conflicting-outputs
    description: Generate code files
    packageFilters:
      dirExists: lib
      dependsOn: "build_runner"

  build:prod:web:
    run: |
      melos exec -c 1 -- \
       flutter build web
    packageFilters:
      dirExists: [lib, web]
      scope: "frontend"
