name: NITO
repository: https://github.com/2rabs/nito

sdkPath: .fvm/flutter_sdk

packages:
  - apps/**
  - packages/**

ide:
  intellij:
    enabled: true
    moduleNamePrefix: nito_

command:
  bootstrap:
    usePubspecOverrides: true
    runPubGetInParallel: true

scripts:
  format:
    run: |
      melos exec -- \
        flutter format --dry-run --set-exit-if-changed lib/
    description: Format in all packages
    select-package:
      flutter: true
      dir-exists: lib

  test:
    run: |
      melos exec --fail-fast -- \
        flutter test --coverage
    description: flutter test in all packages
    select-package:
      flutter: true
      dir-exists: test

  gen:
    run: |
      melos exec -- \
        flutter pub run build_runner build --delete-conflicting-outputs
    description: Generate code files
    select-package:
      dir-exists: lib
      depends-on: "build_runner"
