name: frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  core_common:
    path: ../../packages/core/common
  core_model:
    path: ../../packages/core/model
  core_network:
    path: ../../packages/core/network
  core_data:
    path: ../../packages/core/data
  feature_top:
    path: ../../packages/feature/top
  feature_auth:
    path: ../../packages/feature/auth
  feature_settings:
    path: ../../packages/feature/settings

  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  hooks_riverpod: ^2.0.2
  supabase_flutter: ^1.0.0
  go_router: ^6.0.0
  js: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
