name: feature_top_example
description: Demonstrates how to use the feature_top plugin.
publish_to: 'none'

environment:
  sdk: '<4.0.0'

dependencies:
  flutter:
    sdk: flutter

  feature_top:
    path: ../

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
