name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    paths:
      - 'apps/**'
      - 'packages/**'

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: macos-12

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # 本番環境用の .env を作成
      - name: create .env
        run: |
          touch .env
          echo SUPABASE_URL=${{secrets.SUPABASE_URL}} >> .env
          echo SUPABASE_ANON_KEY=${{secrets.SUPABASE_ANON_KEY}} >> .env
        working-directory: ./apps/frontend

      - name: install fvm
        run: |
          brew tap leoafarias/fvm
          brew install fvm

      # .fvm/fvm_config.json に指定された Flutter をインストール
      - name: setup flutter
        if: ${{ steps.flutter_cache_id.outputs.cache-hit != 'true' }}
        run: fvm install

      # パッケージをキャッシュ or キャッシュから復元
      - name: cache flutter packages
        uses: actions/cache@v3
        id: flutter_packages_cache_id
        env:
          cache-name: cache-flutter-packages
        with:
          path: |
            ${{ env.FLUTTER_HOME }}/.pub-cache
            **/.packages
            **/.flutter-plugins
            **/.flutter-plugin-dependencies
            **/.dart_tool/package_config.json
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}

      # Melos をインストール
      - name: install melos
        run: |
          dart pub global activate melos
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          melos bootstrap

      # Web ビルドを実行
      - name: web build
        run: fvm flutter build web
        working-directory: ./apps/frontend

      # Firebase Hosting にデプロイ
      - id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWORABS_NITO }}'
          projectId: tworabs-nito
