name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'packages/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main

      # 本番環境用の .env を作成
      - name: create .env
        run: |
          touch .env
          echo LIFF_ID=${{secrets.LIFF_ID}} >> .env
          echo SUPABASE_URL=${{secrets.SUPABASE_URL}} >> .env
          echo SUPABASE_ANON_KEY=${{secrets.SUPABASE_ANON_KEY}} >> .env
        working-directory: ./apps/frontend

      - name: Parse Flutter version
        uses: kuhnroyal/flutter-fvm-config-action@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: Prepare Melos
        run: echo "MELOS_SDK_PATH=${{ env.FLUTTER_ROOT }}" >> $GITHUB_ENV

      - name: Install Melos
        uses: bluefireteam/melos-action@v2

      # Web ビルドを実行
      - name: web build
        run: melos run build:prod:web

      # Firebase Hosting にデプロイ
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWORABS_NITO }}'
          channelId: live
          projectId: tworabs-nito
