name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'packages/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: macos-12

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 2

      # 本番環境用の .env を作成
      - name: create .env
        run: |
          touch .env
          echo SUPABASE_URL=${{secrets.SUPABASE_URL}} >> .env
          echo SUPABASE_ANON_KEY=${{secrets.SUPABASE_ANON_KEY}} >> .env
        working-directory: ./apps/frontend

      - name: install fvm
        run: |
          brew tap leoafarias/fvm
          brew install fvm

      # .fvm/fvm_config.json に指定された Flutter をインストール
      - name: setup flutter
        run: fvm install

      # Melos をインストール
      - name: install melos
        run: |
          dart pub global activate melos
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          melos bootstrap

      # Web ビルドを実行
      - name: web build
        run: fvm flutter build web
        working-directory: ./apps/frontend

      # Firebase Hosting にデプロイ
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWORABS_NITO }}'
          channelId: live
          projectId: tworabs-nito
